### PR TITLE
Colormap features

### PR DESCRIPTION
**Pull request by thomgrand**
This pull request features updates to the Color Ramp node. It is now possible to use multiple presets (generated using generate_colormaps.py) that are present in [matplotlib](https://matplotlib.org/stable/tutorials/colors/colormaps.html).
The number of samples from the colormap can be quickly modified using the slider to create a contour-like effect together with constant interpolation. Here is a screenshot of the small additional documentation provided in "Cutting Field Data" in docs/.
pull_request_tmp

Additional notes:
- Changing any of the parameters will overwrite any custom modifications made to the colormap
- This pull request also includes some modifications to the folder structure of the project
- Since I merged this from the dev branch of my repository, there are already some minor inclusions of the pyvista library. The patch should however work without pyvista

### CODE REVIEW

**Comment by tkeskita** [comment]
Hi Thomas,
thanks for the pull request! But it's a huge diff to bite! You got many things going on there, including moving files. I've also just upgraded to VTK 9.0.1 which complicates diffs a bit. I believe you have also other stuff to be merged coming in later? Is your dev branch now finished? Let me think a bit how to proceed with this.

**Comment by thomgrand** [comment]
Yes, I agree. I was also a bit surprised by all the little changes. If you agree with the restructuring of the project, I could submit it as a separate Pull-Request were only files are moved and imports are updated. The colormap feature could then be a separate pull request on top of this restructuring.
The dev branch has some WIP features that could potentially be eliminated, but that still leaves a lot of changes.

**Comment by tkeskita** [comment]
Hi, I had a more close look on your PR, here's my comments, please feel free to comment back:
- Yes would be best to break the pull request to even smaller bits, now there is too many unrelated things happening. Only one "feature" per pull request is optimal (unless they're really short/small ones, can have many as separate commits).
- Separation of generated nodes and custom nodes to own folders is a good idea, since it makes root folder more readable.
- Why move Info node to lonesome ./custom_nodes/helper/info.py? If ./info.py shadows something, then maybe just rename to ./b_info.py (done like that for others)?
- Using the color maps from matplotlib looks like a nice feature! Looking forward to that, I'm sure many people would like it!
- Maybe clean up code lines commented out? But if they are beneficial to have they're ok.
- Error handling change also as a separate pull request. But is BVTKException needed or very beneficial? I mean, I think current pythonic way is to avoid custom exception handlers unless really needed..? Not sure where I got this though. If it's needed, maybe put it to e.g. core.py instead of a lonesome folder and file?
- Try to keep docs minimalistic (only briefly document the features, nothing more). Only add images (in png format for uniformity) where needed (they add maintenance overhead and repo size). It's ok to leave doc updates for later also.

**Comment by thomgrand** [comment]
I think the info node was simply separated since I thought there will be more files moving to the helper folder. 
I agree with you that in it's current form the pull request brings too many unrelated changes in terms of diff. I'll work to make separate smaller pull requests, but will leave this pull request open for further discussion if that's ok. I'd close it once the feature has been fully ported in a separate PR.

**Comment by tkeskita** [comment]
Ok, great! It's good idea to leave this PR open for discussions.

It's usually better to move stuff to new locations when there is clear need or benefit to do it, so maybe info.py is best left at current place for now.

Please note that there's now some activity at my master branch, so let's take this one step at a time. I've found out that [the Coolprop project's github workflow](https://github.com/CoolProp/CoolProp/wiki/Contributing:-git-development-workflow) helps to minimize pains related to changes in master while preparing patches, you may want to check it out.

**Comment by tkeskita** [comment]
For future: Binding with pyvista is OK for extended features, but please make it optional if at all possible.

**Comment by thomgrand** [comment]
I totally agree and planned all features provided through the pyvista library to be completely optional as additional nodes or flags. The colormap feature itself though does not depend on pyvista.

**Comment by thomgrand** [comment]
The features of this branch have been merged in #40 and #41

**Pull request closed without merging**
