### PR TITLE
Fix vtkBoxClipDataSet

### PR DESCRIPTION
**Pull request by vigeesh**
Hi @tkeskita - I have fixed a problem with the vtkBoxClipDataSet filter.

The issue was that the BoxClip property was not exposed to the BVtk nodes.
issue

With this fix, the BoxClip property can be accessed.
fix

Please consider reviewing it and pulling this to your master branch.

### CODE REVIEW

**Comment by tkeskita** [comment]
Hi @vigeesh , thanks for contributing!

1. Please do not modify contents of `gen_VTK*.py`, because they are autogenerated and will be lost when VTK version is changed. Instead, copy code of `class VTKBoxClipDataSet` to `VTKFilters.py` and modify it there.

2. This would add a subclass specific instruction to top level node (BVTK_Node.apply_properties()) which is inherited by all nodes. I would like to keep top level as general, so instead of modifying top level code, you should add a custom `def apply_properties` function to `class VTKBoxClipDataSet`.

BR,
Tuomo

**Comment by vigeesh** [comment]
Hi @tkeskita - thanks for the tip.

I have now appended the VTKFilters with the new class definition and left the top level code untouched.
Please have a look.

**Comment by tkeskita** [comment]
Thanks, committed! I only added small fix for cmd.

**Comment by vigeesh** [comment]
Thanks @tkeskita, I just realized the cmd issue after I committed the changes. The nodes were looking fine otherwise.

**Pull request merged**
